# Site settings
title: devblok
description: "devblok's technical scribbles"
url: 'https://github.com/devblok'
baseurl: '/'
google_analytics: 'UA-146163229-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Lukas Praninskas'
  email: l.praninskas@gmail.com
  twitter_username: 
  facebook_username: lukas.praninskas
  github_username:  devblok
  linkedin_username:  lukas.praninskas

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
